name: Bug report
description: Create a report to help us improve
labels: [bug]

body:
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Have you completed the following steps and are still able to replicate the issue?
      options:
        - label: "Using a stable version of Neovim (i.e. not neovim nightly)"
          required: true
        - label: "`:AstroUpdate`"
          required: true
        - label: Restarted AstroNvim
          required: true
  - type: input
    id: system-version
    attributes:
      label: "Operating system/version"
      placeholder: "macOS 11.5"
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: "Terminal/GUI"
      placeholder: "kitty"
    validations:
      required: true
  - type: textarea
    id: health
    attributes:
      label: AstroNvim Health
      description: Output of `:checkhealth astronvim`
      placeholder: |
        ## AstroNvim
        - INFO: AstroNvim Version: nightly (v2.11.8-181-g11d5990)
        - INFO: Neovim Version: v0.8.3
        - OK: Using stable Neovim >= 0.8.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or recording ([Asciinema](asciinema.org)) to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Add any additional context about the problem here.
