name: Bug report
description: Create a report to help us improve
labels: [bug]

body:
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Have you checked if someone has reported this issue before?
      options:
        - label: I have searched through the AstroNvim docs
          required: true
        - label: I have searched through the existing issues of AstroNvim
          required: true
        - label: I have searched the existing issues of plugins related to this issue
          required: true
  - type: input
    id: neovim-version
    attributes:
      label: "Neovim version (nvim -v)"
      placeholder: "0.9.1 release"
    validations:
      required: true
  - type: input
    id: system-version
    attributes:
      label: "Operating system/version"
      placeholder: "macOS 11.5"
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: "Terminal/GUI"
      placeholder: "kitty"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or recording ([Asciinema](asciinema.org)) to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Add any additional context about the problem here.
  - type: textarea
    attributes:
      label: Repro
      description: Minimal `init.lua` to reproduce this issue. Save as `repro.lua` and run with `nvim -u repro.lua`
      value: |
        -- save as repro.lua
        -- run with nvim -u repro.lua
        -- DO NOT change the paths
        local root = vim.fn.fnamemodify("./.repro", ":p")

        -- set stdpaths to use .repro
        for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
          vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
        end

        -- bootstrap lazy
        local lazypath = root .. "/plugins/lazy.nvim"
        if not vim.loop.fs_stat(lazypath) then
          -- stylua: ignore
          vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
        end
        vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

        -- install plugins
        local plugins = {
          { "AstroNvim/AstroNvim", branch = "v4", import = "astronvim.plugins" },

          -- add any other plugins/customizations here
        }
        require("lazy").setup(plugins, {
          root = root .. "/plugins",
        })

        -- add anything else here (autocommands, vim.filetype, etc.)
      render: Lua
    validations:
      required: false
