blank_issues_enabled: false
contact_links:
  - name: r/AstroNvim (Reddit)
    url: https://www.reddit.com/r/AstroNvim
    about: Ask questions about AstroNvim on the official Subreddit
  - name: Discord Chat
    url: https://discord.astronvim.com
    about: Ask questions and have discussions about AstroNvim on Discord
