blank_issues_enabled: true

contact_links:
  - name: Reddit community
    url: https://www.reddit.com/r/AstroNvim
    about: Ask questions about AstroNvim on Reddit
  - name: Discord community
    url: https://discord.gg/UcZutyeaFW
    about: Discussions about AstroNvim on Discord
