name: Feature request
description: Suggest an idea for this project
labels: [enhancement]

body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature related to a problem?
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: solution
    attributes:
      label: Describe the new feature
      placeholder: A clear and concise description of what the new feature is.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
