name: Question
description: Ask a general question about AstroNvim usage
labels: [question]

body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
  - type: textarea
    id: user-config
    attributes:
      label: User Configuration
      description: "Please include your `user/init.lua` file here if relevant"
      placeholder: |
        ```lua
        local config = {
          header = "My Custom Config",
        }

        return config
        ```
