return {
  BufferLineFill = { fg = C.grey_9, bg = C.grey_4 },
  BufferLineBackground = { fg = C.grey_9, bg = C.grey_4 },
  BufferLineBufferVisible = { fg = C.fg, bg = C.bg },
  BufferLineBufferSelected = { fg = C.white, bg = C.bg, bold = true },
  BufferLineTab = { fg = C.grey_9, bg = C.bg },
  BufferLineTabSelected = { fg = C.fg, bg = C.bg },
  BufferLineTabClose = { fg = C.red_4, bg = C.bg },
  BufferLineIndicatorSelected = { fg = C.bg, bg = C.bg },
  BufferLineSeparator = { fg = C.grey_4, bg = C.grey_4 },
  BufferLineSeparatorVisible = { fg = C.bg, bg = C.bg },
  BufferLineSeparatorSelected = { fg = C.grey_4, bg = C.grey_4 },
  BufferLineCloseButton = { fg = C.grey_9, bg = C.grey_4 },
  BufferLineCloseButtonVisible = { fg = C.grey_10, bg = C.bg },
  BufferLineCloseButtonSelected = { fg = C.red_4, bg = C.bg },
  BufferLineModified = { fg = C.red_4, bg = C.grey_4 },
  BufferLineModifiedVisible = { fg = C.fg, bg = C.bg },
  BufferLineModifiedSelected = { fg = C.green_2, bg = C.bg },
  BufferLineError = { fg = C.red_1, bg = C.red_1 },
  BufferLineErrorDiagnostic = { fg = C.red_1, bg = C.red_1 },
}
