return {
  DapUIVariable = { fg = C.fg },
  DapUIScope = { link = "Title" },
  DapUIType = { link = "Type" },
  DapUIValue = { fg = C.red },
  DapUIModifiedValue = { fg = C.yellow_1, bold = true },
  DapUIDecoration = { fg = C.grey_1 },
  DapUIThread = { link = "String" },
  DapUIStoppedThread = { link = "Title" },
  DapUIFrameName = { link = "Normal" },
  DapUISource = { link = "Keyword" },
  DapUILineNumber = { link = "Number" },
  DapUIFloatBorder = { link = "FloatBorder" },
  DapUIWatchesEmpty = { fg = C.red_1 },
  DapUIWatchesValue = { fg = C.orange_1 },
  DapUIWatchesError = { fg = C.red_1 },
  DapUIBreakpointsPath = { link = "Title" },
  DapUIBreakpointsInfo = { fg = C.white_2 },
  DapUIBreakpointsCurrentLine = { fg = C.yellow_1, bold = true },
  DapUIBreakpointsLine = { link = "DapUILineNumber" },
  DapUIBreakpointsDisabledLine = { link = "Comment" },
}
