return {
  NotifyBackground = { bg = C.bg },
  NotifyERRORBorder = { fg = C.red },
  NotifyWARNBorder = { fg = C.orange_1 },
  NotifyINFOBorder = { fg = C.green },
  NotifyDEBUGBorder = { fg = C.cyan },
  NotifyTRACERBorder = { fg = C.purple },
  NotifyERRORIcon = { fg = C.red },
  NotifyWARNIcon = { fg = C.orange_1 },
  NotifyINFOIcon = { fg = C.green },
  NotifyDEBUGIcon = { fg = C.cyan },
  NotifyTRACEIcon = { fg = C.purple },
  NotifyERRORTitle = { fg = C.red },
  NotifyWARNTitle = { fg = C.orange_1 },
  NotifyINFOTitle = { fg = C.green },
  NotifyDEBUGTitle = { fg = C.cyan },
  NotifyTRACETitle = { fg = C.purple },
  NotifyERRORBody = { fg = C.fg },
  NotifyWARNBody = { fg = C.fg },
  NotifyINFOBody = { fg = C.fg },
  NotifyDEBUGBody = { fg = C.fg },
  NotifyTRACEBody = { fg = C.fg },
  NotifyLogTime = { fg = C.grey_2 },
  NotifyLogTitle = { fg = C.blue },
}
