return {
  MacroRecording = "Recording:",
  ActiveLSP = "LSP:",
  BufferClose = "x",
  NeovimClose = "X",
  DefaultFile = "[F]",
  DiagnosticError = "X",
  DiagnosticHint = "?",
  DiagnosticInfo = "i",
  DiagnosticWarn = "!",
  Ellipsis = "...",
  FileModified = "*",
  FileReadOnly = "[lock]",
  FolderClosed = "[D]",
  FolderEmpty = "[E]",
  FolderOpen = "[O]",
  GitAdd = "[+]",
  GitChange = "[/]",
  GitDelete = "[-]",
  GitConflict = "[!]",
  GitIgnored = "[I]",
  GitRenamed = "[R]",
  GitStaged = "[S]",
  GitUnstaged = "[U]",
  GitUntracked = "[?]",
}
