return {
  CmpItemAbbrDefault = { fg = C.fg },
  CmpItemAbbrDeprecatedDefault = { fg = C.grey_2 },
  CmpItemAbbrMatchDefault = { fg = C.white },
  CmpItemAbbrMatchFuzzyDefault = { fg = C.white },
  CmpItemKind = { fg = C.yellow },
  CmpItemAbbr = { fg = C.fg },
  CmpItemMenuDefault = { fg = C.fg },
  CmpItemAbbrDeprecated = { fg = C.fg, strikethrough = true },
  CmpItemAbbrMatch = { fg = C.blue, bg = C.menu },
  CompeDocumentation = { link = "Pmenu" },
  CompeDocumentationBorder = { link = "Pmenu" },
  CmpItemKindMethod = { link = "TSMethod" },
  CmpItemKindText = { link = "TSString" },
  CmpItemKindFunction = { link = "TSFunction" },
  CmpItemKindConstructor = { link = "TSType" },
  CmpItemKindVariable = { link = "TSVariable" },
  CmpItemKindClass = { link = "TSType" },
  CmpItemKindInterface = { link = "TSType" },
  CmpItemKindModule = { link = "TSNamespace" },
  CmpItemKindProperty = { link = "TSProperty" },
  CmpItemKindOperator = { link = "TSOperator" },
  CmpItemKindReference = { link = "TSParameterReference" },
  CmpItemKindUnit = { link = "TSField" },
  CmpItemKindValue = { link = "TSField" },
  CmpItemKindField = { link = "TSField" },
  CmpItemKindEnum = { link = "TSField" },
  CmpItemKindKeyword = { link = "TSKeyword" },
  CmpItemKindSnippet = { link = "TSText" },
  CmpItemKindColor = { link = "cssColor" },
  CmpItemKindFile = { link = "TSURI" },
  CmpItemKindFolder = { link = "TSURI" },
  CmpItemKindEvent = { link = "TSConstant" },
  CmpItemKindEnumMember = { link = "TSField" },
  CmpItemKindConstant = { link = "TSConstant" },
  CmpItemKindStruct = { link = "TSStructure" },
  CmpItemKindTypeParameter = { link = "TSParameter" },
}
