-- HACK: Remove after upstream PR gets merged
-- https://github.com/nvim-tree/nvim-web-devicons/pull/264
return {
  "nvim-tree/nvim-web-devicons",
  enabled = vim.g.icons_enabled,
  opts = {
    override_by_filename = {
      [".babelrc"] = { icon = "" },
      ["r"] = { icon = "󰟔" },
      ["webpack"] = { icon = "󰜫" },
    },
    override_by_extension = {
      ["cs"] = { icon = "󰌛" },
      ["csv"] = { icon = "󰈙" },
      ["doc"] = { icon = "󰈬" },
      ["docx"] = { icon = "󰈬" },
      ["json5"] = { icon = "" },
      ["material"] = { icon = "󰔉" },
      ["mint"] = { icon = "󰌪" },
      ["opus"] = { icon = "󰈣" },
      ["pdf"] = { icon = "" },
      ["ppt"] = { icon = "󰈧" },
      ["r"] = { icon = "󰟔" },
      ["rproj"] = { icon = "󰗆" },
      ["scm"] = { icon = "󰘧" },
      ["sv"] = { icon = "󰍛" },
      ["svh"] = { icon = "󰍛" },
      ["svg"] = { icon = "󰜡" },
      ["tbc"] = { icon = "󰛓" },
      ["tcl"] = { icon = "󰛓" },
      ["tex"] = { icon = "󰙩" },
      ["tscn"] = { icon = "󰎁" },
      ["txt"] = { icon = "󰈙" },
      ["v"] = { icon = "󰍛" },
      ["vh"] = { icon = "󰍛" },
      ["vhd"] = { icon = "󰍛" },
      ["vhdl"] = { icon = "󰍛" },
      ["webpack"] = { icon = "󰜫" },
      ["xls"] = { icon = "󰈛" },
      ["xlsx"] = { icon = "󰈛" },
      ["xml"] = { icon = "󰗀" },
      ["sol"] = { icon = "󰞻" },
      ["prisma"] = { icon = "󰔶" },
      ["log"] = { icon = "󰌱" },
    },
  },
}
