return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
        "bash",
        "haskell",
        "markdown",
        "toml",
        "yaml",
        "lua",
        "python",
        "java",
        "javascript",
        "typescript",
        "c",
        "cpp",
        "rust",
        "scss",
        "swift",
        "ruby",
        "php",
        "make",
        "json",
        "html",
        "graphql",
        "go",
        "erlang",
        "elixir",
        "eex",
        "heex",
        "surface",
        "dockerfile",
    },
  },
}
