name: Documentation

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: 5.4
      - name: Install LDoc
        uses: leafo/gh-actions-luarocks@v4
      - name: Setup dependencies
        run: luarocks install ldoc
      - name: Build Docs
        run: |
          ldoc .
      - name: Deploy
        uses: nwtgck/actions-netlify@v2.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: docs
          production-deploy: ${{ github.ref == 'refs/heads/main' }}
